### ISSUE TITLE
Run rustfmt on entire workspace

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#108]
Consider doing this on `master` after #107 and #94 are merged in. Would be nice to establish this as a merge requirement now that I got `rustfmt` working on my system.

I discovered we can have Travis fail if the code is not properly formatted. Might be over-aggressive? Other option is to just manually require it (like we commonly have for "no new warnings") after we run it on the entire workspace.

https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by Manghi** [comment]
`netwayste` and `dissect-netwayste` have received this TLC.

**Comment by AaronM04** [comment]
I think we should 1) get it set up so that it shows up as a failed check in PRs if any of the files are not rustfmted, then 2) have a single commit that rustfmts all .rs files in the repo. Ideally with a distinctive author name for visibility in git blame, etc.

**Comment by AaronM04** [comment]
Useful link: https://crate-ci.github.io/pr/rustfmt.html

Also TIL that unlike gofmt, rustfmt is configurable! There's really only two options I think we should change from the default:
* max line length from 100 to 120, and
* struct_field_align_threshold to 20 (or at least pick a value between 10 and 25 or so)

**Comment by Manghi** [comment]
>I think we should 1) get it set up so that it shows up as a failed check in PRs if any of the files are not rustfmted, then 2) have a single commit that rustfmts all .rs files in the repo. Ideally with a distinctive author name for visibility in git blame, etc.

Sounds good to me. Could we also specify the files/folders that were formatted? Something like: 
`[rustfmt] username: client.rs and all of conwayste/ui/`

> Also TIL that unlike gofmt, rustfmt is configurable! There's really only two options I think we should change from the default:

I'm fine with both of those configurations. 20 sounds good to me for `struct_field_align_threshold`.

I would also like to add:
* `empty_item_single_line` to false
* `enum_discrim_align_threshold` to the same as `struct_field_align_threshold`
