### ISSUE TITLE
Cargo.lock merge conflicts 

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#123]
@AaronM04 

Seems that the past few PR's I've had to deal with quite a bit of merge conflicts in `Cargo.lock` b/c dependabot pushes `master` forward but the development branches get left behind.

Can we define when dependabot should run (weekly? monthly?), or perhaps allow it in to run in non-master branches. I'm open to ideas to get out of this `Cargo.lock` merge conflict pain that I keep dealing with.

**Comment by Manghi** [comment]
![image](https://user-images.githubusercontent.com/1715672/83311956-a78ebc00-a1c5-11ea-854c-4f57d3f5e425.png)

I merged in `master` last week into the `aaron/dissector` branch, and so it's not very clear to me why `libc` was bumped up but `pkg-config` seemed to be downgraded. Really hard to figure out which of the two I should keep.

**Comment by AaronM04** [comment]
I think the easiest way to deal with a merge conflict is (assuming you're still merging):

1) checkout the Cargo.lock from your branch
2) cargo build
3) git add Cargo.lock
4) git commit

On May 29, 2020 4:00:02 PM PDT, Manghi <notifications@github.com> wrote:
>@AaronM04 
>
>Seems that the past few PR's I've had to deal with quite a bit of merge
>conflicts in `Cargo.lock` b/c dependabot pushes `master` forward but
>the development branches get left behind.
>
>Can we define when dependabot should run (weekly? monthly?), or perhaps
>allow it in to run in non-master branches. I'm open to ideas to get out
>of this `Cargo.lock` merge conflict pain that I keep dealing with.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/conwayste/conwayste/issues/123

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Manghi** [comment]
Thanks that did the trick. Still puzzled about those changes since neither `alsa-sys`, `libc` or `pkg-config` was modified by dependabot recently after I looked through the recent PR's.
