### ISSUE TITLE
Windows install instructions in readme

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#17]
The installation instructions are a bit scanty on details; for example, where to get the SDL2 libraries.

I suggest copying from https://github.com/Rust-SDL2/rust-sdl2#user-content-windows-msvc

**Comment by Manghi** [comment]
ggez is no longer using SDL2. Revisit when closer to release.

**Comment by Manghi** [comment]
We're removing Windows support for 1.0 in order to focus our sights on a playable game.
