### ISSUE TITLE
Fullscreen on Windows 10 resizes windows

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#18]
I just tested it on Windows 10. I went into fullscreen mode then quit, and all the windows on the monitor it displayed on got their sizes shrunk to fit some smaller size. Very annoying!

I think we should comment out fullscreen as an option if we can't fix that...

**Comment by Manghi** [comment]
ggez switched from SDL2 to winit.
Open a new ticket if issue persists with winit.
Closing as obsolete.
