### ISSUE TITLE
Server processes a request infinitely

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#190]
**Describe the bug**
The Conwayste server gets stuck processing (infinitely) the same request over and over again even though the client only sends it once. Maybe not a big deal since this entire stack is being rewritten.

**To Reproduce**
- Run the `cli-client` and conwayste `server
- Type any networked command like a chat message or `/connect`
- Gracefully stop or kill the client
- Server will be continue to process the same command over and over again

**Your Environment:**
Broken on `master`. Discovered while working on `dependabot/cargo/tokio-1.2.0` update.

**Comment by Manghi** [comment]
Was working in after upgrading from Futures 0.2 to 0.3 (c3b778848d557027ce0f0e671c46d0cee9fd7215).
Broke after the upgrade from Tokio 0.2 to 0.3 (230decb43bd86fa3553dc2b92c7f3af5d875d844).

**Comment by Manghi** [comment]
I figured out why its "repeating infinitely". I'm not advancing the  `src: &BytesMut` buffer in the codec's `decode(..) ` implementation. In 0.3 and newer, Tokio switched over to` BytesMut` which requires that the source buffer be drained/advanced by the codec during serialization. Right now we're using `serde` and `bincode` for [de]serialization so I need to figure out how to get the length of what was deserialized. There's a crate that's supposed to help with this (`tokio_serde`).

**Comment by AaronM04** [comment]
I tried out your `am/issue190` branch and it seems to fix the issue! 🎉
