### ISSUE TITLE
Splash screen and graphics settings resolution/scaling is broken

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#26]
- Splash screen not centered
- Splash screen universe is currently built using gameplay universe settings (like zoom level)
- Graphics settings overlap on option and current selection

**Comment by Manghi** [comment]
Resizing window while still in game breaks drawing by adding a strange offset.

1. Select Start Game
2. Change resolution to anything other than the current resolution
3. Resume Game

**Comment by AaronM04** [comment]
> Graphics settings overlap on option and current selection

This one is fixed in the `aaron/gui_fixes` branch (although we may scrap all this menu code anyway).

**Comment by Manghi** [comment]
* Splash screen (aka intro screen) is now centered except for in full screen.
* Splash screen is no longer coupled to gameplay universe settings

**Comment by Manghi** [comment]
Merged to master. :heavy_check_mark: 
Closing.
