### ISSUE TITLE
MTU discovery

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#43]
We need to discover the MTU (maximum transfer unit) in both directions between client and server.

**IPv4**: find the largest packet size that doesn't get dropped when DF (Don't Fragment) bit is set to 1, as illustrated in [this video that's, like, sooooooo 2009](https://www.youtube.com/watch?v=K4fKzuY9tx8). The`-l` flag to the `ping` command lets you specify the packet length, and `-f` sets the DF bit, [according to Microsoft](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping).

**IPv6**: we don't have support for this yet, but when we do, we'll need to find the MTU as well. It's very different from IPv4 in this respect: [IPv6 MTU Gotchas and other ICMP issues](https://blogs.cisco.com/enterprise/ipv6-mtu-gotchas-and-other-icmp-issues)

**What to do when the packet is too large**: for now, we can log an error, and display it to the user. There is a separate issue (#24) for packet fragmentation and reassembly.

**Comment by Manghi** [comment]
Minor note to the reader: #24 is actually #42 in this newly submerged repo.

**Comment by Manghi** [comment]
Just pick a size for Conwayste 1.0 (see AaronM04's comment from May 2, 2019).
Leaving open in case we want to address this after 1.0.

**Comment by Manghi** [comment]
I'm deciding to leave this alone for now. Instead of selecting the MTU based on network conditions, we should just pick a size that will work in most cases. Supporting varying sizes based on client/server capability can be an added improvement down the road.
