### ISSUE TITLE
Netwayste Integration into Conwayste

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#46]
After #16 is merged...

1. Convert `client.rs` and `net.rs` into a library API 
    (`server.rs` remains an executable)
2. Re-organize unit tests
3. Add documentation
4. Hook into `conwayste\conwayste`

**Comment by AaronM04** [comment]
Both are merged now! @Manghi :grinning:

**Comment by Manghi** [comment]
What a joy to hear!
