### ISSUE TITLE
TextField calculates its text width via Context

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#69]
Categorizing as a `bug`/`enhancement` as this code could be improved. Relies on https://github.com/ggez/ggez/issues/583 to be first fixed.

ggez's monospaced fonts do not calculate each character's width as expected (each char width should be the size of the `Uniform::scale(..)`).

Once fixed, we should be able to use the default font scale width to calculate the length of a text rather than to pass through `Context` to get the width like we do for a `TextField.`

**Comment by AaronM04** [comment]
Can this be closed?

**Comment by Manghi** [comment]
Fixed by @AaronM04  via 3f00acd .
