### ISSUE TITLE
Fix on_click handling

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#76]
If you click in a top-level widget's rect, it should be propagated down the widget tree until it reaches a rect that 1) contains the click region, and 2) handles on_click (we could change the function signature to return bool - true means it was handled and should not be propagated)

Remove the `if on_hover {` stuff.

**Comment by Manghi** [comment]
From offline conversation:

The parent should be calling `within_widget()` for each child to decide whether to call that child's `on_click()` handler. There would then be no need for the child to call `within_widget()` or check its hovering status before handling an `on_click()` event.
